### ISSUE TITLE
Loss calculation has an index error

### ISSUE THREAD

**Issue by zhouhao-learning** [selimsef/dsb2018_topcoders#10]
Hello, I am very happy to see your code, I am trying to implement it, I downloaded the cells and data through Kaggle, and got the mask and label, I executed `/albu/src/train_all.bash` according to your instructions, but I got the following error:
```
Traceback (most recent call last):
  File "bowl_train.py", line 120, in <module>
    train_bowl()
  File "bowl_train.py", line 97, in train_bowl
    train(ds, val_ds, fold, train_idx, val_idx, config, num_workers=num_workers, transforms=aug_victor(.97))
  File "/scratch2/hzhou/DPNUnet/dsb2018_topcoders/albu/src/pytorch_utils/train.py", line 345, in train
    trainer.fit(train_loader, val_loader, config.nb_epoch)
  File "/scratch2/hzhou/DPNUnet/dsb2018_topcoders/albu/src/pytorch_utils/train.py", line 290, in fit
    self.metrics_collection.train_metrics = self._run_one_epoch(epoch, train_loader, training=True)
  File "/scratch2/hzhou/DPNUnet/dsb2018_topcoders/albu/src/pytorch_utils/train.py", line 256, in _run_one_epoch
    meter, ypreds = self._make_step(data, training)
  File "/scratch2/hzhou/DPNUnet/dsb2018_topcoders/albu/src/pytorch_utils/train.py", line 276, in _make_step
    meter, ypreds = self.estimator.make_step_itersize(images, ytrues, training)
  File "/scratch2/hzhou/DPNUnet/dsb2018_topcoders/albu/src/pytorch_utils/train.py", line 207, in make_step_itersize
    meter = self.calculate_loss_softmax(output, target, meter, training, iter_size)
  File "/scratch2/hzhou/DPNUnet/dsb2018_topcoders/albu/src/pytorch_utils/train.py", line 135, in calculate_loss_softmax
    meter['loss'] += loss.data.cpu().numpy()[0]
IndexError: too many indices for array

```

I output a `loss.data.cpu().numpy()`, I get a number instead of an array or list:

Why is this reason? Can you guide me in detail?

**Comment by dkermany** [comment]
I am also encountering this error. @albu @selimsef

**Comment by selimsef** [comment]
in new Pytorch version `loss.item()` should be used to obtain scalar value

**Comment by dkermany** [comment]
I "solved" it by removing the indexing call for those lines but not sure if that's proper.

e.g.
meter['loss'] += loss.data.cpu().numpy()

**Comment by dkermany** [comment]
@selimsef Thanks for the prompt reply!

**Comment by selimsef** [comment]
You can look at the differences from the old pytorch 
https://medium.com/the-artificial-impostor/pytorch-0-4-0-release-1-0-preview-86ca50441b0b
Regarding this issue:
`Use .item() to get the Python number from a scaler variable instead of .data[0].`
